### ISSUE TITLE
Updated value not reflecting in the Next Rules where method

### ISSUE THREAD

**Issue by banandh** [evrete/evrete#72]
Hi - I'm trying to run https://github.com/itz-priyanshi-garg/Evrete_Rule_Engine/tree/main/EvreteTransaction this sample code in local.

In my use case I have updated the fact value inside the action. When the next rule is executed, in the "where" method i expected the fact value should have the updated value but its not taking up the updated instead it uses the old value and run's incorrect action. 

Code updates only in TransactionRules.
RequestBody 
{

    "transactionAmount":110,
    "transactionCount":100
}

 @Rule(salience = 1)
    @Where(value = { "$t.transactionAmount > 100"})
    public void ruleRangeVoid(Transaction $t, Commission $c)
    {
        $c.setCommissionAmount(0);
        $c.setCommissionPercentage(0);
        **$t.setTransactionCount( $t.getTransactionAmount()-80);      // Here updated the transaction amount to 30 (110-80)**
        $c.setResponseMessage("Transaction Count is invalid");
    }

When the next set of rule executes , it should go into  @Where(value = { "$t.transactionCount >= 21", "$t.transactionCount <= 30"})
   and return the commission percentage as 6 but it retains the original value of 110 and fires    @Where(value = {"$t.transactionCount > 40"}) action and ended up with commissionpercentage of 10.

**Comment by andbi** [comment]
Hi, just like with most rule engines, you need to explicitly tell the engine that a fact was updated. In your particular case you need to include an additional `RhsContext` variable in your method declaration and call the `ctx.update()` method.

https://evrete.org/apidocs/3.0.05/org/evrete/api/RhsContext.html#update(java.lang.Object)

**Comment by banandh** [comment]
Thanks @andbi . It works. But now the rule is evaluating recursively.


transactionAmount grater than 100
transactionAmount grater than 30
transactionAmount grater than 100
transactionAmount grater than 30
transactionAmount grater than 100
transactionAmount grater than 30
transactionAmount grater than 100
transactionAmount grater than 30
transactionAmount grater than 100.

Code changes
  @Rule(salience = 1)
    @Where(value = { "$t.transactionAmount > 100"})
    public void ruleRangeVoid(Transaction $t, Commission $c , RhsContext ctx)
    {
        System.out.println("transactionAmount grater than 100");
        $c.setCommissionAmount(0);
        $c.setCommissionPercentage(0);
        $t.setTransactionCount( $t.getTransactionAmount()-80);
        $c.setResponseMessage("Transaction Count is invalid");
        ctx.update($c); ctx.update($t);


    }

**Comment by andbi** [comment]
Yes, that usually happens if updated facts meet the same conditions. It's often useful to treat updates as a sequence of delete+insert operations, and if the updated facts pass through the very same conditions, the recursion is inevitable. 

The solution is usually simple, just make sure that your conditions work only for non-updated facts. You might need to add an extra numeric condition or a "processed" flag of some sort.
