### ISSUE TITLE
Performance Issue with createCondition

### ISSUE THREAD

**Issue by kuldeeparora89** [evrete/evrete#79]
Hi,

I have a scenario where I need to load rules from the excel & build the knowledge rule set dynamically . 
Basically each row in excel will be a rule with cell representing the conditions & actions.
I am able to build the rule set but it is running very slow -

Code Snippet-

```
List<String> whereExpressions = inputColumns.stream()
						.map(c -> prepareWhereExpression(c, m.get(c), schema.get(c), "$v")).filter(e->e!=null&&!"".equals(e)).toList();
				List<EvaluatorHandle> handles = whereExpressions.stream().map(e->{
					try {
						return builder.createCondition(e);
					} catch (CompilationException e1) {
						// TODO Auto-generated catch block
						throw new RuntimeException(e);
					}
				}).toList()  ;
```

I have checked & createCondition is taking most of the time . My excel has 3000+ rows with 10 condition columns so 10*3000 createCondition calls.

Version - 3.0.06

**Comment by andbi** [comment]
Hi! The solution is already on the way. 

Historically, the library used to launch Java compiler for each condition independently, now it batch-compiles all conditions of a rule in a single run. 

The next version will compile rulesets as if they were a single multi-file Java project, a with similar compile time.

ETA: 1-2 weeks



The next

**Comment by kuldeeparora89** [comment]
Thanks @andbi  ,it seems promising . I will wait for the next version.

**Comment by evrete** [comment]
@kuldeeparora89 almost there, ETA 24-48 hours

**Comment by andbi** [comment]
@kuldeeparora89 almost there, ETA 24-48 hours

**Comment by andbi** [comment]
Version 3.1.00 has now been released. It contains several significant changes. 

Given your advanced usage, you will need to update your code slightly. Rather than calling `createCondition` on each rule builder, please use the https://evrete.org/apidocs/3.1.00/org/evrete/api/RuntimeContext.html#compile(java.util.Collection) method to compile all your conditions at once. The documentation is relatively straightforward, and considering that the rule builders extend the `Rule` interface, you should encounter no issues compiling all 30,000 conditions in one pass.

Please do not hesitate to reach out if you require further assistance.

**Comment by andbi** [comment]
The code seems ok except the 'compile' part. Why do you need it? The `build()` method will compile everything, including conditions.

**Comment by andbi** [comment]
Ok. It was a misunderstanding then. You don't need to use the `compile` method when building a knowledge from scratch. The `build` method will do everything for you. 

However, if you want to get condition handles (like in your first snippet) and reference/change them in your code later, then the `compile` method is how you do that.

Could you please check if everything's ok without the extra
`compile` call? I will create several new tests based on your use case, but it's important that you get what's expected. Thank you.

**Comment by kuldeeparora89** [comment]
Got it now , working code -
	
```
		try {
		data.forEach(m -> {

				// 1. Creating a rule and getting its condition handle
				RuleBuilder<Knowledge> builder = ruleSetBuilder.newRule("Rule " + data.indexOf(m))
						.property("ACTIVATION-GROUP", "AG1");
				LhsBuilder<Knowledge> lhsBuilder = builder.forEach("$v", Map.class);
			
				List<String> whereExpressions = inputColumns.stream()
						.map(c -> prepareWhereExpression(c, m.get(c), Commons.isEmpty(schema.get(c))?"String":schema.get(c), "$v"))
						.filter(e -> e != null && !"".equals(e)).toList();

				 lhsBuilder.where(whereExpressions.toArray(new String[] {}));
				lhsBuilder.execute(ctx -> {
					outputColumns.forEach(c -> {
						Map o = ctx.get("$v");
						o.put(c, m.get(c));
					});
					
					ctx.deleteFact("$v");

				});
		});
		knowledge=ruleSetBuilder.build();

```
Thanks @andbi  , working like a charm now.

**Comment by andbi** [comment]
Great! How fast is it now, btw? I haven't measured it myself, my guess the new builder should be at least 10x faster in your case.

**Comment by kuldeeparora89** [comment]
Yes reduced a lot . 9.4 sec in my case.
